spring:
  config:
    activate:
      on-profile: local
    import: application-oauth2.yml
  datasource:
    url: jdbc:h2:tcp://localhost/~/smeme-server
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        auto_quote_keyword: true

logging.level:
  org.hibernate.SQL: debug