spring:
  config:
    activate:
      on-profile: dev
    import: application-oauth2.yml
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        auto_quote_keyword: true

logging.level:
  org.hibernate.SQL: debug

fcm:
  file_path: smeem_fcm.json
  url: https://fcm.googleapis.com/v1/projects/smeem-303d1/messages:send