spring:
  config:
    import: application-secret.yml
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE.ENDPOINT_URL.dev}:5432/postgres?currentSchema=${DATABASE.NAME.dev}
    username: ${DATABASE.USERNAME.dev}
    password: ${DATABASE.PASSWORD.dev}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        auto_quote_keyword: true

logging.level:
  org.hibernate.SQL: debug

fcm:
  file_path: smeem_fcm.json
  url: ${FCM.URL}
  google_api: https://www.googleapis.com/auth/cloud-platform
  smeem_title: "오늘의 영어 훈련, 딱 5분 걸려요!"
  smeem_body: "지금 눌러서 일기 쓰기 ✍️"

jwt:
  secret: ${JWT.SECRET}
  KAKAO_URL: https://kapi.kakao.com/v2/user/me
  APPLE_URL: https://appleid.apple.com/auth/keys
  ACCESS_TOKEN_EXPIRED: 7200000
  REFRESH_TOKEN_EXPIRED: 1209600000

badge:
  welcome-badge-id: ${WELCOME_BADGE_ID}

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    url: /docs/open-api-3.0.1.json
    path: /swagger

smeem:
  duration:
    expired: ${SMEEM.DURATION.EXPIRED}
    remind: ${SMEEM.DURATION.REMIND}