spring:
  config:
    import: application-secret.yml
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE.ENDPOINT_URL.prod}:5432/postgres?currentSchema=${DATABASE.NAME.prod}
    username: ${DATABASE.USERNAME.prod}
    password: ${DATABASE.PASSWORD.prod}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        auto_quote_keyword: true

logging.level:
  org.hibernate.SQL: debug

fcm:
  file_path: firebase/smeem_fcm.json
  project_id: ${FCM.PROJECT_ID}
  url: ${FCM.URL}
  google_api: https://www.googleapis.com/auth/cloud-platform

jwt:
  secret: ${JWT.SECRET}
  KAKAO_URL: https://kapi.kakao.com/v2/user/me
  APPLE_URL: https://appleid.apple.com/auth/keys
  ACCESS_TOKEN_EXPIRED: 7200000
  REFRESH_TOKEN_EXPIRED: 1209600000

badge:
  welcome-badge-id: ${WELCOME_BADGE_ID}

smeem:
  duration:
    expired: ${SMEEM.DURATION.EXPIRED}
    remind: ${SMEEM.DURATION.REMIND}
  client:
    version:
      title: "업데이트 알림"
      content: "보다 나아진 스밈의 최신 버전을 준비했어요! 새로운 버전으로 업데이트 후 이용해주세요."
      ios:
        app: 2.0.1
        force: 2.0.0 # 심사 통과 후 3.0.0 업데이트 필요
  notification:
    title: "오늘의 영어 훈련, 딱 5분 걸려요!"
    body: "지금 눌러서 일기 쓰기 ✍️"
    cron_expression: "0 0/30 * * * *"
  badge:
    update_cron_expression: "0 0 04 1 * *"

discord:
  webhook:
    error-url: ${DISCORD.WEBHOOK_ERROR_URL}
    info-url: ${DISCORD.WEBHOOK_INFO_URL}

sentry:
  dsn: ${SENTRY.DSN}
  environment: prod
  enable-tracing: true
  exception-resolver-order: -2147483647