springdoc:
  packages-to-scan: com.smeem.http
  swagger-ui:
    path: /api-docs
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true

spring:
  jackson:
    default-property-inclusion: NON_NULL

#webhook:
#  slack:
#    url: ${SLACK_HOOK_URL} TODO: discord 연결
