name: deploy-prod

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: Create application-secret.yml
        run: |
          pwd
          cd ./smeem-bootstrap/src/main/resources
          touch ./application-secret.yml
          echo "${{ secrets.APPLICATION_SECRET_YML }}" >> ./application-secret.yml
          cat ./application-secret.yml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create FireBase JSON file From AWS
        run: |
          aws s3 cp --region ap-northeast-2 s3://${{ secrets.AWS_PROD_BUCKET_NAME }}/json/smeem_fcm.json smeem-notification/src/main/resources/firebase-config/smeem_fcm.json

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://${{ secrets.AWS_PROD_BUCKET_NAME }}/deploy/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name smeem-codedeploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name prod-group
          --s3-location bucket=${{ secrets.AWS_PROD_BUCKET_NAME }},bundleType=zip,key=deploy/$GITHUB_SHA.zip
