name: pr-check

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: create application-oauth2 file
        working-directory: ./
        run: |
          pwd
          touch src/main/resources/application-oauth2.yml
          echo secret=${{ secrets.secret }} >> src/main/resources/application-oauth2.yml
          echo KAKAO_URL=${{ secrets.KAKAO_URL }} >> src/main/resources/application-oauth2.yml
          cat src/main/resources/application-oauth2.yml

      - name: Create application.yml
        run: |
          pwd
          touch src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_YML }}" >> src/main/resources/application.yml
          cat src/main/resources/application.yml

      - name: Create FireBase JSON file
        run: |
          pwd
          touch src/main/resources/smeem_fcm.json
          echo "${{ secrets.FCM_JSON }}" >> src/main/resources/smeem_fcm.json
          cat src/main/resources/smeem_fcm.json

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash