name: deploy-dev

on:
  push:
    branches: [ develop ] #TODO: change trigger

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: Create application-secret.yml
        run: |
          pwd
          cd ./smeem-bootstrap/src/main/resources
          touch ./application-secret.yml
          echo "${{ secrets.APPLICATION_SECRET_YML }}" >> ./application-secret.yml
          cat ./application-secret.yml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create FireBase JSON file From AWS
        run: |
          aws s3 cp --region ap-northeast-2 s3://${{ secrets.AWS_BUCKET_NAME }}/json/smeem_fcm.json smeem-notification/src/main/resources/firebase-config/smeem_fcm.json

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test
        shell: bash

      - name: Set docker
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login docker
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME_DEV }}
          password: ${{ secrets.DOCKERHUB_LOGIN_ACCESSTOKEN_DEV }}

      - name: Build docker image
        run: |
          docker build --platform linux/amd64 -t smeemdev/smeem-dev:latest -f Dockerfile-prod .
          docker push smeemdev/smeem-dev:latest

  deploy-cd:
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - name: SSH로 서버 접속
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RELEASE_SERVER_IP_DEV }}
          username: ${{ secrets.RELEASE_SERVER_USER_DEV }}
          key: ${{ secrets.RELEASE_SERVER_KEY_DEV }}
          script: |
            cd ~

            # deploy.sh 파일 다운로드
            wget https://raw.githubusercontent.com/Team-Smeme/Smeme-server-renewal/develop/script/deploy.sh -O deploy.sh
            chmod +x deploy.sh

            # .env 파일 추가
            if ! grep -q "REGISTRY_URL=" .env; then
              echo "REGISTRY_URL=${{ secrets.IMAGE_NAME_DEV }}" >> .env
            fi
            if ! grep -q "IMAGE_NAME=" .env; then
              echo "IMAGE_NAME=${{ secrets.REGISTRY_URL_DEV }}" >> .env
            fi

            # 배포 스크립트 실행
            sudo ./deploy.sh
